import { RUN_TOKEN_HEADER } from '@agent-band/contracts';
import { AGY_CLAUDE_NAME_OF, AGY_UNCHECKABLE_TOOLS } from '../../runner/agy-tools.ts';

/**
 * Source of the Antigravity PreToolUse hook command. The policy speaks Claude tool names, so built-in
 * agy tools are renamed (and their path arguments aliased) before the authorize-tool call.
 * Every problem prints an explicit deny; a crash exits 2, a non-zero exit that agy treats as a deny.
 */
export function agyHookScript(opts: { port: number; runId: string }): string {
  const url = `http://127.0.0.1:${opts.port}/api/v1/runs/${opts.runId}/authorize-tool`;
  return `// Generated by agent-band. Fails closed: any problem denies the tool call.
const URL_ = ${JSON.stringify(url)};
const RUN_ID = ${JSON.stringify(opts.runId)};
const TOKEN = process.env.AGENT_BAND_RUN_TOKEN || '';
const CLAUDE_NAME_OF = ${JSON.stringify(AGY_CLAUDE_NAME_OF)};
const UNCHECKABLE = ${JSON.stringify(AGY_UNCHECKABLE_TOOLS)};
const PATH_KEYS = ['AbsolutePath', 'TargetFile'];

function finish(output, code) {
  process.stdout.write(output, () => process.exit(code));
}
function deny(reason) {
  finish(JSON.stringify({ decision: 'deny', reason: 'agent-band: ' + reason }), 0);
}

setTimeout(() => deny('authorization timed out'), 8000).unref();
process.on('uncaughtException', () => {
  process.stderr.write('agent-band: hook failed', () => process.exit(2));
});

function str(v) {
  return typeof v === 'string' && v ? v : undefined;
}

/** The path argument: a known key first, then any *Path/*Dir/*Directory/*File key. */
function pathOf(args) {
  for (const key of PATH_KEYS) if (str(args[key])) return args[key];
  for (const [key, value] of Object.entries(args)) {
    if (/(Path|Dir|Directory|File)$/.test(key) && str(value)) return value;
  }
  return undefined;
}

/** The name and input the policy understands, or null when the call cannot be judged. */
function normalize(call) {
  const args = call.args && typeof call.args === 'object' ? call.args : {};
  const name = CLAUDE_NAME_OF[call.name];
  if (!name) return null;
  if (name === 'Bash') return { name, input: { command: str(args.CommandLine) } };
  if (name === 'WebFetch') return { name, input: { url: str(args.Url) } };
  if (name === 'WebSearch') return { name, input: { query: str(args.query) } };
  const path = pathOf(args);
  if (!path) return null;
  if (name === 'Glob' || name === 'Grep') return { name, input: { path } };
  return { name, input: { file_path: path } };
}

async function main() {
  if (!TOKEN) return deny('missing run token');
  let raw = '';
  for await (const chunk of process.stdin) raw += chunk;
  const call = JSON.parse(raw).toolCall;
  if (!call || typeof call.name !== 'string' || !call.name) return deny('invalid hook input');
  if (UNCHECKABLE.includes(call.name)) return deny('tool ' + call.name + ' is not supported under policy');
  const judged = normalize(call);
  if (!judged) return deny('tool ' + call.name + ' cannot be checked against the policy');
  const res = await fetch(URL_, {
    method: 'POST',
    headers: { 'content-type': 'application/json', ${JSON.stringify(RUN_TOKEN_HEADER)}: TOKEN },
    body: JSON.stringify({ runId: RUN_ID, toolName: judged.name, toolInput: judged.input }),
    signal: AbortSignal.timeout(5000),
  });
  if (res.status !== 200) return deny('authorization service returned ' + res.status);
  const body = await res.json();
  if (body && body.decision === 'allow') return finish(JSON.stringify({ decision: 'allow' }), 0);
  if (body && body.decision === 'deny') {
    return deny(typeof body.reason === 'string' ? body.reason : 'denied by policy');
  }
  return deny('invalid authorization response');
}

main().catch((err) => deny('authorization unavailable: ' + (err && err.message ? err.message : 'error')));
`;
}
