import { RUN_TOKEN_HEADER } from '@agent-band/contracts';
import { CLAUDE_NAME_OF, GEMINI_UNCHECKABLE_TOOLS } from '../../runner/gemini-tools.ts';

/**
 * Source of the Gemini BeforeTool hook command. The policy speaks Claude tool names, so built-in
 * Gemini tools are renamed (and their path arguments aliased) before the authorize-tool call.
 * Every problem prints an explicit deny; a crash exits 2, which Gemini treats as a block.
 */
export function geminiHookScript(opts: { port: number; runId: string }): string {
  const url = `http://127.0.0.1:${opts.port}/api/v1/runs/${opts.runId}/authorize-tool`;
  return `// Generated by agent-band. Fails closed: any problem denies the tool call.
const URL_ = ${JSON.stringify(url)};
const RUN_ID = ${JSON.stringify(opts.runId)};
const TOKEN = process.env.AGENT_BAND_RUN_TOKEN || '';
const CLAUDE_NAME_OF = ${JSON.stringify(CLAUDE_NAME_OF)};
const UNCHECKABLE = ${JSON.stringify(GEMINI_UNCHECKABLE_TOOLS)};

function finish(output, code) {
  process.stdout.write(output, () => process.exit(code));
}
function deny(reason) {
  finish(JSON.stringify({ decision: 'deny', reason: 'agent-band: ' + reason }), 0);
}

setTimeout(() => deny('authorization timed out'), 8000).unref();
process.on('uncaughtException', () => {
  process.stderr.write('agent-band: hook failed', () => process.exit(2));
});

function str(v) {
  return typeof v === 'string' && v ? v : undefined;
}

/** The name and input the policy understands. */
function normalize(input) {
  const raw = input.tool_name;
  const args = input.tool_input && typeof input.tool_input === 'object' ? input.tool_input : {};
  const mcp = input.mcp_context && typeof input.mcp_context === 'object' ? input.mcp_context : null;
  const server = mcp ? str(mcp.server_name) : undefined;
  if (server) {
    let tool = str(mcp.tool_name) || raw;
    for (const prefix of ['mcp_' + server + '_', server + '__']) {
      if (tool.startsWith(prefix)) tool = tool.slice(prefix.length);
    }
    return { name: 'mcp__' + server + '__' + tool, input: args };
  }
  const name = CLAUDE_NAME_OF[raw];
  if (!name) return { name: raw, input: args };
  if (name === 'Bash') return { name, input: { ...args, command: str(args.command) } };
  if (name === 'Glob' || name === 'Grep') {
    return { name, input: { ...args, path: str(args.dir_path) || str(args.path) } };
  }
  return { name, input: { ...args, file_path: str(args.file_path) || str(args.absolute_path) || str(args.path) } };
}

async function main() {
  if (!TOKEN) return deny('missing run token');
  let raw = '';
  for await (const chunk of process.stdin) raw += chunk;
  const input = JSON.parse(raw);
  if (typeof input.tool_name !== 'string' || !input.tool_name) return deny('invalid hook input');
  if (UNCHECKABLE.includes(input.tool_name)) return deny('tool ' + input.tool_name + ' is not supported under policy');
  const call = normalize(input);
  const res = await fetch(URL_, {
    method: 'POST',
    headers: { 'content-type': 'application/json', ${JSON.stringify(RUN_TOKEN_HEADER)}: TOKEN },
    body: JSON.stringify({ runId: RUN_ID, toolName: call.name, toolInput: call.input }),
    signal: AbortSignal.timeout(5000),
  });
  if (res.status !== 200) return deny('authorization service returned ' + res.status);
  const body = await res.json();
  if (body && body.decision === 'allow') return finish('', 0);
  if (body && body.decision === 'deny') {
    return deny(typeof body.reason === 'string' ? body.reason : 'denied by policy');
  }
  return deny('invalid authorization response');
}

main().catch((err) => deny('authorization unavailable: ' + (err && err.message ? err.message : 'error')));
`;
}
