import { RUN_TOKEN_HEADER } from '@agent-band/contracts';

/**
 * Source of the PreToolUse hook command. Allow prints nothing (normal permission flow
 * continues); everything else, including any error, prints an explicit deny.
 */
export function hookScript(opts: { port: number; runId: string }): string {
  const url = `http://127.0.0.1:${opts.port}/api/v1/runs/${opts.runId}/authorize-tool`;
  return `// Generated by agent-band. Fails closed: any problem denies the tool call.
const URL_ = ${JSON.stringify(url)};
const RUN_ID = ${JSON.stringify(opts.runId)};
const TOKEN = process.env.AGENT_BAND_RUN_TOKEN || '';

function finish(output, code) {
  process.stdout.write(output, () => process.exit(code));
}
function deny(reason) {
  finish(
    JSON.stringify({
      hookSpecificOutput: {
        hookEventName: 'PreToolUse',
        permissionDecision: 'deny',
        permissionDecisionReason: 'agent-band: ' + reason,
      },
    }),
    0,
  );
}

setTimeout(() => deny('authorization timed out'), 8000).unref();
process.on('uncaughtException', () => {
  process.stderr.write('agent-band: hook failed', () => process.exit(2));
});

async function main() {
  if (!TOKEN) return deny('missing run token');
  let raw = '';
  for await (const chunk of process.stdin) raw += chunk;
  const input = JSON.parse(raw);
  if (typeof input.tool_name !== 'string' || !input.tool_name) return deny('invalid hook input');
  const res = await fetch(URL_, {
    method: 'POST',
    headers: { 'content-type': 'application/json', ${JSON.stringify(RUN_TOKEN_HEADER)}: TOKEN },
    body: JSON.stringify({
      runId: RUN_ID,
      toolName: input.tool_name,
      toolInput: input.tool_input,
      toolUseId: typeof input.tool_use_id === 'string' ? input.tool_use_id : undefined,
    }),
    signal: AbortSignal.timeout(5000),
  });
  if (res.status !== 200) return deny('authorization service returned ' + res.status);
  const body = await res.json();
  if (body && body.decision === 'allow') return finish('', 0);
  if (body && body.decision === 'deny') {
    return deny(typeof body.reason === 'string' ? body.reason : 'denied by policy');
  }
  return deny('invalid authorization response');
}

main().catch((err) => deny('authorization unavailable: ' + (err && err.message ? err.message : 'error')));
`;
}

export const HOOKS_JSON = {
  hooks: {
    PreToolUse: [
      {
        matcher: '*',
        hooks: [
          {
            type: 'command',
            command: 'node "${CLAUDE_PLUGIN_ROOT}/hooks/authorize-tool.mjs"',
            timeout: 10,
          },
        ],
      },
    ],
  },
} as const;
